In [7]:
import numpy as np

In [76]:
a = [x for x in "AATCCC"]
b = [x for x in "GGTGAAT"]
a, b

(['A', 'A', 'T', 'C', 'C', 'C'], ['G', 'G', 'T', 'G', 'A', 'A', 'T'])

In [77]:
x = np.array(a)
x

array(['A', 'A', 'T', 'C', 'C', 'C'], 
      dtype='<U1')

In [78]:
y = np.array(b)
z = np.vstack(y)
z

array([['G'],
       ['G'],
       ['T'],
       ['G'],
       ['A'],
       ['A'],
       ['T']], 
      dtype='<U1')

In [84]:
np.array([x,z])

array([array(['A', 'A', 'T', 'C', 'C', 'C'], 
      dtype='<U1'),
       array([['G'],
       ['G'],
       ['T'],
       ['G'],
       ['A'],
       ['A'],
       ['T']], 
      dtype='<U1')], dtype=object)

In [81]:
compare = x == z
compare

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False,  True, False, False, False]], dtype=bool)

In [83]:
endsmatch = np.diagonal(compare, offset=-4)
endsmatch.all()

True

In [69]:
c = [x for x in "AATCCC"]
d = [x for x in "AACGCAA"]
c, d

(['A', 'A', 'T', 'C', 'C', 'C'], ['A', 'A', 'C', 'G', 'C', 'A', 'A'])

In [70]:
e = np.array(a)
f = np.vstack(b)

In [71]:
e,f

(array(['A', 'A', 'T', 'C', 'C', 'C'], 
       dtype='<U1'), array([['A'],
        ['A'],
        ['C'],
        ['G'],
        ['C'],
        ['A'],
        ['A']], 
       dtype='<U1'))

In [72]:
compared = e==f
compared

array([[ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False]], dtype=bool)

In [87]:
nodiag = np.diagonal(compared, offset=-4)
nodiag

array([False,  True, False], dtype=bool)

In [85]:
g = [x for x in "AATCCC"]
h = [x for x in "AATGCAA"]
k = np.array(g)
m = np.vstack(h)
wrongend = k==m
wrongend

array([[ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False]], dtype=bool)

In [88]:
wrongdiag = np.diagonal(wrongend, offset=-4)
wrongdiag

array([False,  True, False], dtype=bool)

In [89]:
s = np.array([x for x in "AATCCC"])
t = np.vstack([x for x in "CCCGGG"])
otherend = s==t
otherend

array([[False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [99]:
upperright = np.diagonal(otherend, offset=3)
upperright

array([ True,  True,  True], dtype=bool)

In [ ]:
#question: how to ensure using the correct diagonal regardless of sequence length?