In [7]:
import numpy as np

In [76]:
a = [x for x in "AATCCC"]
b = [x for x in "GGTGAAT"]
a, b

(['A', 'A', 'T', 'C', 'C', 'C'], ['G', 'G', 'T', 'G', 'A', 'A', 'T'])

In [77]:
x = np.array(a)
x

array(['A', 'A', 'T', 'C', 'C', 'C'], 
      dtype='<U1')

In [78]:
y = np.array(b)
z = np.vstack(y)
z

array([['G'],
       ['G'],
       ['T'],
       ['G'],
       ['A'],
       ['A'],
       ['T']], 
      dtype='<U1')

In [84]:
np.array([x,z])

array([array(['A', 'A', 'T', 'C', 'C', 'C'], 
      dtype='<U1'),
       array([['G'],
       ['G'],
       ['T'],
       ['G'],
       ['A'],
       ['A'],
       ['T']], 
      dtype='<U1')], dtype=object)

In [81]:
compare = x == z
compare

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False,  True, False, False, False]], dtype=bool)

In [83]:
endsmatch = np.diagonal(compare, offset=-4)
endsmatch.all()

True

In [69]:
c = [x for x in "AATCCC"]
d = [x for x in "AACGCAA"]
c, d

(['A', 'A', 'T', 'C', 'C', 'C'], ['A', 'A', 'C', 'G', 'C', 'A', 'A'])

In [70]:
e = np.array(a)
f = np.vstack(b)

In [71]:
e,f

(array(['A', 'A', 'T', 'C', 'C', 'C'], 
       dtype='<U1'), array([['A'],
        ['A'],
        ['C'],
        ['G'],
        ['C'],
        ['A'],
        ['A']], 
       dtype='<U1'))

In [72]:
compared = e==f
compared

array([[ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False]], dtype=bool)

In [87]:
nodiag = np.diagonal(compared, offset=-4)
nodiag

array([False,  True, False], dtype=bool)

In [85]:
g = [x for x in "AATCCC"]
h = [x for x in "AATGCAA"]
k = np.array(g)
m = np.vstack(h)
wrongend = k==m
wrongend

array([[ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False, False, False, False]], dtype=bool)

In [88]:
wrongdiag = np.diagonal(wrongend, offset=-4)
wrongdiag

array([False,  True, False], dtype=bool)

In [89]:
s = np.array([x for x in "AATCCC"])
t = np.vstack([x for x in "CCCGGG"])
otherend = s==t
otherend

array([[False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [99]:
upperright = np.diagonal(otherend, offset=3)
upperright

array([ True,  True,  True], dtype=bool)

In [ ]:
#question: how to ensure using the correct diagonal regardless of sequence length?
#diagonal is exactly the same length as the top
#offset is len(top) - 3 (for top right)
#other direction is -(first offset-1) (I think) 

In [100]:
        q= np.array([x for x in 'ACCGAGCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCT'])
        r = np.vstack([x for x in 'CCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGA'])
        endmatch = q==r
        endmatch

array([[False,  True,  True, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False, False, False, ..., False, False,  True],
       ..., 
       [False,  True,  True, ...,  True,  True, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]], dtype=bool)

In [106]:
offset = len(q) - 3
np.diagonal(endmatch, offset=offset)

array([ True,  True,  True], dtype=bool)

In [103]:
eight = np.array([1,2,3,4,5,6,7,8])
nine = np.vstack([6,7,8,0,0,0,0,0])
eq = eight==nine
eq

array([[False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]], dtype=bool)

In [104]:
np.diagonal(eq)

array([False, False, False, False, False, False, False, False], dtype=bool)

In [105]:
offset = len(eight) - 3
np.diagonal(eq, offset=offset)

array([ True,  True,  True], dtype=bool)

In [108]:
#longer overlap (with no overlap on the very ends) is coming back as a match, which means it's not working 
#the way I want it to
CA_1 = np.array([x for x in 'ACCGAGCGCCACCATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAA'])
CA_2 = np.vstack([x for x in 'GGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGG'])
long = CA_1 == CA_2

In [109]:
long

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [111]:
offset = len(CA_1) -3
thing = np.diagonal(long, offset=offset)
thing

array([False, False, False], dtype=bool)

In [112]:
thing.all() == True

False

In [115]:
otheroffset = -(offset-1)
nothing = np.diagonal(long, offset=otheroffset)
nothing

array([], dtype=bool)

In [114]:
nothing.all() == True

True

In [117]:
wtf = np.array([])
wtf

array([], dtype=float64)

In [118]:
wtf.all() == True

True

In [119]:
[]==True

False

In [121]:
all([])==True

True

In [122]:
len([])==0

True

In [124]:
0==True

False

In [125]:
[]==False

False

In [127]:
test = [True, True, False, False]
test.count(True)

2