In [1]:
import numpy as np

In [4]:
one =('a', 'GGTGCCCATCCTGGTCGAG')
two = ('b', 'GGTCGAGCTGGACGG')

In [5]:
a = np.array([x for x in one[1]])
b = np.vstack([x for x in two[1]])
compared = a==b

In [7]:
compared

array([[ True,  True, False,  True, False, False, False, False, False,
        False, False, False,  True,  True, False, False,  True, False,
         True],
       [ True,  True, False,  True, False, False, False, False, False,
        False, False, False,  True,  True, False, False,  True, False,
         True],
       [False, False,  True, False, False, False, False, False,  True,
        False, False,  True, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True, False, False,
         True,  True, False, False, False, False,  True, False, False,
        False],
       [ True,  True, False,  True, False, False, False, False, False,
        False, False, False,  True,  True, False, False,  True, False,
         True],
       [False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False,  True,
        False],
       [ True,  True, False,  True, False, False, Fa

In [15]:
offset = len(one[1]) - 3

In [16]:
endsmatch = np.diagonal(compared, offset=-(offset-1))

In [17]:
endsmatch

array([], dtype=bool)

In [19]:
len(one[1])

19

In [20]:
otherendsmatch = np.diagonal(compared, offset=offset)
otherendsmatch

array([ True, False, False], dtype=bool)

In [23]:
otheroffset = len(two[1]) - 3
otheroffset

12

In [24]:
np.diagonal(compared, offset=otheroffset)

array([ True,  True,  True,  True,  True,  True,  True], dtype=bool)